'use strict';
var validate = (function() {
  var refVal = [];
  return function validate(data, dataPath, parentData, parentDataProperty, rootData) {
    'use strict';
    validate.errors = null;
    return true;
  };
})();
validate.schema = {
  "Release": "00603",
  "DocumentType": 521,
  "TransactionSet": [{
    "ID": "ST",
    "Min": 0
  }, {
    "ID": "BGN"
  }, {
    "ID": "BPR",
    "Min": 0
  }, {
    "ID": "NTE",
    "Min": 0,
    "Max": "unbounded"
  }, {
    "ID": "TRN",
    "Min": 0
  }, {
    "ID": "CUR",
    "Min": 0
  }, {
    "ID": "REF",
    "Min": 0,
    "Max": "unbounded"
  }, {
    "ID": "DTM",
    "Min": 0,
    "Max": "unbounded"
  }, {
    "ID": "AD1",
    "Min": 0,
    "Max": "unbounded"
  }, {
    "ID": "N1Loop1",
    "Min": 0,
    "Max": "unbounded",
    "Loop": [{
      "ID": "N1"
    }, {
      "ID": "N2",
      "Min": 0,
      "Max": 2
    }, {
      "ID": "N3",
      "Min": 0,
      "Max": 2
    }, {
      "ID": "N4",
      "Min": 0
    }, {
      "ID": "REF",
      "Min": 0,
      "Max": "unbounded"
    }, {
      "ID": "PER",
      "Min": 0,
      "Max": "unbounded"
    }]
  }, {
    "ID": "NM1Loop1",
    "Max": "unbounded",
    "Loop": [{
      "ID": "NM1"
    }, {
      "ID": "N2",
      "Min": 0,
      "Max": 2
    }, {
      "ID": "IN2",
      "Min": 0,
      "Max": "unbounded"
    }, {
      "ID": "N3",
      "Min": 0,
      "Max": 2
    }, {
      "ID": "N4",
      "Min": 0
    }, {
      "ID": "REF",
      "Min": 0,
      "Max": "unbounded"
    }, {
      "ID": "DTM",
      "Min": 0,
      "Max": "unbounded"
    }, {
      "ID": "AD1",
      "Min": 0,
      "Max": "unbounded"
    }, {
      "ID": "MSG",
      "Min": 0,
      "Max": "unbounded"
    }, {
      "ID": "PAMLoop1",
      "Min": 0,
      "Max": "unbounded",
      "Loop": [{
        "ID": "PAM"
      }, {
        "ID": "REF",
        "Min": 0,
        "Max": "unbounded"
      }, {
        "ID": "DTM",
        "Min": 0,
        "Max": "unbounded"
      }]
    }, {
      "ID": "CDSLoop1",
      "Min": 0,
      "Max": "unbounded",
      "Loop": [{
        "ID": "CDS"
      }, {
        "ID": "REF",
        "Min": 0,
        "Max": "unbounded"
      }, {
        "ID": "PAM",
        "Min": 0,
        "Max": "unbounded"
      }, {
        "ID": "DTM",
        "Min": 0,
        "Max": "unbounded"
      }, {
        "ID": "N1Loop2",
        "Min": 0,
        "Max": "unbounded",
        "Loop": [{
          "ID": "N1"
        }, {
          "ID": "N2",
          "Min": 0,
          "Max": 2
        }, {
          "ID": "IN2",
          "Min": 0,
          "Max": "unbounded"
        }, {
          "ID": "N3",
          "Min": 0,
          "Max": 2
        }, {
          "ID": "N4",
          "Min": 0
        }, {
          "ID": "REF",
          "Min": 0,
          "Max": "unbounded"
        }, {
          "ID": "PER",
          "Min": 0,
          "Max": "unbounded"
        }]
      }]
    }]
  }, {
    "ID": "AMT",
    "Min": 0
  }, {
    "ID": "SE",
    "Min": 0
  }]
};
validate.errors = null;
module.exports = validate;